import CssBaseline from "@mui/material/CssBaseline";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<meta name="viewport" content="initial-scale=1, width=device-width" />
			</head>
			<body>
				<CssBaseline>{children}</CssBaseline>
			</body>
		</html>
	);
}
